AWS_ACCESS_KEY_ID: ENTER_HERE
AWS_SECRET_ACCESS_KEY: ENTER_HERE

AWS_CONFIG_BUCKET: ENTER_HERE # Bucket to use to place config files

DATABRICKS_HOST: ENTER_HERE
DATABRICKS_TOKEN: ENTER_HERE
DATABRICKS_CLUSTER_ID: ENTER_HERE

SNOWFLAKE:
  USER: ENTER_HERE
  PASSWORD: ENTER_HERE
  ACCOUNT: ENTER_HERE (Organization-Account)